spring:
  datasource:
    url: jdbc:mysql://localhost:3306/highway?serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: localhost
      port: 6379
      password: 000000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.microvideo.framework3.project.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl